name: Pluto-ensemble
favicon: null
layout_spectrum: 0.24629
typography_spectrum: 0.60025
title: Pluto - ensemble
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#323a83'
    - '#b36f84'
    - '#c0beaf'
    - '#e6988c'
  brandStrength: 0.625
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
