name: Pluto-ensemble
favicon: null
layout_spectrum: 0.02785
typography_spectrum: 0.59766
title: Pluto - ensemble
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72875420-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#472935'
    - '#ac6670'
    - '#838bde'
    - '#e8cdee'
  brandStrength: 1
  lightness: 1
  saturation: 0.9375
  rhythmicContrast: 0
purpose: []
