name: Pluto-ensemble
favicon: null
layout_spectrum: 0.25124
typography_spectrum: 0.5953
title: Pluto - ensemble
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#472935'
    - '#ac6670'
    - '#838bde'
    - '#e8cdee'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.9375
  rhythmicContrast: 0.75
purpose: []
