name: Pluto-ensemble
favicon: null
layout_spectrum: 0.11827846546657383
typography_spectrum: 0.6079
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.717826696112752
  rhythmicContrast: 0.7912024834658951
purpose: []
