name: Pluto-ensemble
favicon: null
layout_spectrum: 0.11827846546657383
typography_spectrum: 0.6079
title: Home
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#323a83'
    - '#b36f84'
    - '#c0beaf'
    - '#e6988c'
  brandStrength: 0.875
  lightness: 0.8125
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
