name: Pluto-ensemble
favicon: null
layout_spectrum: 0.50484
typography_spectrum: 0.59766
title: Pluto - ensemble
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72875420-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#feffff'
    - '#000033'
    - '#774b58'
    - '#868b85'
    - '#d2d8ca'
  brandStrength: 0.25
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
