typography_spectrum: 0.6147
color:
  brandColors:
    - '#feffff'
    - '#000033'
    - '#774b58'
    - '#868b85'
    - '#d2d8ca'
  brandStrength: 0.375
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.37077
analytics:
  google: UA-72875420-1
  facebook: null
  twitter: null
author:
  name: MDC
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e2d6b699-9d99-43a4-a087-7ba203d4bda3.ps
name: Pluto-ensemble
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Program info
    id: 40bd5942-d27e-4e2a-b148-ec46dd7f1e28
    type: content
  - name: Pluto & Hathor
    id: 8e80c2b1-281a-4c06-b81b-d2d40c133df5
    type: content
  - name: Contact
    id: fd6ed8e6-112b-4f8b-a295-0fa38334aaa3
    type: content
favicon: null
title: variable vocal ensemble
purpose: []
