typography_spectrum: 0.60209
color:
  brandColors:
    - '#25064D'
    - '#36175E'
    - '#553285'
    - '#7B52AB'
    - '#9768D1'
  brandStrength: 0.8549742568284273
  lightness: 0.26481626695021987
  saturation: 0.5977110425010324
  rhythmicContrast: 0.6403939209412783
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.13287
analytics:
  google: UA-72875420-1
  facebook: null
  twitter: null
author:
  name: MDC
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/533cf5b5-653f-422c-adde-6fd1305b0b6f.jpg
name: Pluto - ensemble
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Pluto & Hathor
    id: 8e80c2b1-281a-4c06-b81b-d2d40c133df5
    type: content
  - name: Projects
    id: 5215c1d6-be10-48bd-b3a4-f3dc1b5352cd
    type: content
  - name: Photos
    id: 6bb7bc4c-6f4e-478e-83c2-32ee0e73086d
    type: content
  - name: Video
    id: 046dda0e-5c73-4543-9cc7-3eb17608e403
    type: content
  - name: Listen
    id: 85149188-f573-4c30-a8ef-246db8d0e459
    type: content
  - name: Marnix
    id: ff184e56-3f5d-41ff-9645-7651ba420558
    type: content
  - name: Contact
    id: fd6ed8e6-112b-4f8b-a295-0fa38334aaa3
    type: content
favicon: null
title: ''
description: variable vocal ensemble
purpose: []
